/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    Grid: typeof import('./src/components/Grid/Grid.vue')['default']
    GridItem: typeof import('./src/components/Grid/GridItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyModal: typeof import('./src/components/Modal/MyModal.vue')['default']
    MyModel: typeof import('./src/components/MyModel.vue')['default']
    MyTable: typeof import('./src/components/Table/MyTable.vue')['default']
    SearchForm: typeof import('./src/components/Table/SearchForm.vue')['default']
    SearchFormItem: typeof import('./src/components/Table/SearchFormItem.vue')['default']
  }
}
